baseURL                = "https://momin09.github.io/"
languageCode           = "ko-kr"
title                  = "KIM HOMIN | DevOps Blog"
defaultContentLanguage = "en"
hasCJKLanguage         = true

theme = "hugo-theme-stack"

# 다국어(ja/zh) 파일 및 불필요한 기본 테마 콘텐츠 제외
ignoreFiles = [
    '\\.ja\\.md$',
    '\\.zh\\.md$',
    '\\.zh-hant-tw\\.md$',
    'content/categories/Documentation',
    'content/page/links',
]

[taxonomies]
    category = "categories"
    tag      = "tags"

[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug"

[minify]
    disableXML = true

[params]
    mainSections  = ["post"]
    rssFullContent = true
    favicon       = "img/avatar.png"
