[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/momin09"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "email"
    name       = "Email"
    url        = "mailto:khm0909z@gmail.com"

    [social.params]
        icon = "mail"
